# Generated by Django 6.0.6 on 2026-06-25 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255, verbose_name='Quận/Huyện')),
                ('date', models.DateField(verbose_name='Ngày cúp điện')),
                ('start_time', models.TimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Thời gian kết thúc')),
                ('area', models.TextField(verbose_name='Khu vực/Phường xã bị ảnh hưởng')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Trạng thái')),
            ],
            options={
                'unique_together': {('district', 'date', 'start_time', 'end_time', 'area')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=50)),
                ('province_name', models.CharField(max_length=255)),
                ('district_code', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=255)),
                ('ward_code', models.CharField(max_length=50)),
                ('ward_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'province_code', 'district_code', 'ward_code')},
            },
        ),
    ]
