# Generated by Django 6.0.6 on 2026-06-25 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='area_name',
            field=models.CharField(blank=True, help_text='Tên Ấp / Khu vực cụ thể', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'province_code', 'district_code', 'ward_code', 'area_name')},
        ),
    ]
